services:
  postgres:
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
