services:
  app:
    image: cosmtrek/air
    working_dir: /project-package
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    volumes:
      - ./backend/:/project-package/
      - .env:/project-package/.env
    entrypoint: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y libwebp-dev &&
      air
      "

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    ports:
      - "${PGADMIN_PORT}:80"

  objstorage:
    image: quay.io/minio/minio
    env_file: .env
    volumes:
      - "minio_data:/data"
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_data:
    driver: local
