services:
  postgres:
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    depends_on:
      - postgres

  objstorage:
    image: quay.io/minio/minio
    env_file: .env
    volumes:
      - "minio_data:/data"
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
    driver: local
  minio_data:
    driver: local
